"""Initial migrations

Revision ID: 048aa493c43b
Revises: 51127101a757
Create Date: 2023-05-02 20:39:28.479300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '048aa493c43b'
down_revision = '51127101a757'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
