"""empty message

Revision ID: 049acdb9f410
Revises: 2c070d2f8775
Create Date: 2023-11-13 14:44:55.277597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "049acdb9f410"
down_revision: Union[str, None] = "2c070d2f8775"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "book",
        "author",
        existing_type=sa.INTEGER(),
        type_=sa.String(),
        existing_nullable=True,
    )
    op.create_foreign_key(None, "book", "author", ["author"], ["name"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "book", type_="foreignkey")
    op.alter_column(
        "book",
        "author",
        existing_type=sa.String(),
        type_=sa.INTEGER(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
