"""second migration

Revision ID: 059092914d1a
Revises: 92809cd61b20
Create Date: 2023-05-03 13:32:40.787939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "059092914d1a"
down_revision = "92809cd61b20"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
