"""init

Revision ID: 06ddbbd6d5ad
Revises: cf2be48ab742
Create Date: 2023-05-03 17:35:55.371513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06ddbbd6d5ad'
down_revision = 'cf2be48ab742'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
