"""fix models

Revision ID: 0ce2584aec8f
Revises: c212797215a8
Create Date: 2023-05-03 21:50:57.713069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ce2584aec8f'
down_revision = 'c212797215a8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
