"""Added field books to Author model VERSION 2

Revision ID: 133cafaf47e9
Revises: 8d69ab31325d
Create Date: 2023-04-07 15:56:25.056886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '133cafaf47e9'
down_revision = '8d69ab31325d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
