"""Add publication date to Book model

Revision ID: 1478ee044727
Revises: 562b36c6fa68
Create Date: 2023-05-03 11:05:34.212693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1478ee044727'
down_revision = '562b36c6fa68'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
