"""Initial migration

Revision ID: 156be971537f
Revises: 562273b75eb7
Create Date: 2023-05-01 23:30:20.138326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '156be971537f'
down_revision = '562273b75eb7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('title', sa.String(length=255), nullable=False))
    op.drop_column('book', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('name', sa.VARCHAR(length=255), nullable=False))
    op.drop_column('book', 'title')
    # ### end Alembic commands ###
