"""Change

Revision ID: 164124aef1df
Revises: a4ddd1e6c8eb
Create Date: 2023-05-13 21:28:31.852220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '164124aef1df'
down_revision = 'a4ddd1e6c8eb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('author', sa.Column('books', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'author', 'book', ['books'], ['id'])
    op.alter_column('book', 'summary',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('book', 'publication_date',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('book', 'publication_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('book', 'summary',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_constraint(None, 'author', type_='foreignkey')
    op.drop_column('author', 'books')
    # ### end Alembic commands ###
