"""Initial migration

Revision ID: 2360ccbc48b3
Revises: fbfc03fd795b
Create Date: 2024-02-08 19:22:57.994295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2360ccbc48b3'
down_revision: Union[str, None] = 'fbfc03fd795b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_author_id'), 'author', ['id'], unique=False)
    op.create_index(op.f('ix_book_id'), 'book', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_book_id'), table_name='book')
    op.drop_index(op.f('ix_author_id'), table_name='author')
    # ### end Alembic commands ###
