"""Third migration

Revision ID: 309f81f62418
Revises: 5d9947d8208c
Create Date: 2023-05-03 18:42:15.147912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '309f81f62418'
down_revision = '5d9947d8208c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
