"""Initial migration

Revision ID: 30a64be9a97c
Revises: a88c3a30f79a
Create Date: 2023-05-12 11:31:41.809464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30a64be9a97c'
down_revision = 'a88c3a30f79a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
