"""Initial

Revision ID: 37a3384e21ef
Revises: 40198c6ee99c
Create Date: 2023-11-06 14:12:00.075438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "37a3384e21ef"
down_revision: Union[str, None] = "40198c6ee99c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "author",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("bio", sa.String(length=511), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_table(
        "book",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=1023), nullable=False),
        sa.Column("summary", sa.String(length=127), nullable=False),
        sa.Column("publication_date", sa.Date(), nullable=False),
        sa.Column("author_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["author.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
