"""Initial migration

Revision ID: 3d14399948ba
Revises: eddf3f919f9b
Create Date: 2023-11-02 17:08:34.686630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3d14399948ba"
down_revision: Union[str, None] = "eddf3f919f9b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "book", "publication_date", existing_type=sa.DATE(), nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "book", "publication_date", existing_type=sa.DATE(), nullable=True
    )
    # ### end Alembic commands ###
