"""Initial migration

Revision ID: 571fccb73a90
Revises: 9ad7278ac696
Create Date: 2023-07-10 22:43:18.546728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '571fccb73a90'
down_revision = '9ad7278ac696'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
