"""second migration

Revision ID: 58f6c4cf7eb3
Revises: 05f6a968f4e4
Create Date: 2023-05-04 00:42:04.373278

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58f6c4cf7eb3'
down_revision = '05f6a968f4e4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
