"""Second migrationi

Revision ID: 5d9947d8208c
Revises: ee0bfaafb756
Create Date: 2023-05-03 18:09:40.186300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d9947d8208c'
down_revision = 'ee0bfaafb756'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
