"""Initial migration

Revision ID: 5d9999964856
Revises: ec87d0a4daa8
Create Date: 2023-04-30 18:32:56.641530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d9999964856'
down_revision = 'ec87d0a4daa8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_authors_id'), 'authors', ['id'], unique=False)
    op.create_index(op.f('ix_books_id'), 'books', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_books_id'), table_name='books')
    op.drop_index(op.f('ix_authors_id'), table_name='authors')
    # ### end Alembic commands ###
