"""author bio can be nullable, book pub date and authr cannot be nullable

Revision ID: 6dbea825494e
Revises: bd641f727ed0
Create Date: 2023-05-12 16:25:52.375700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6dbea825494e'
down_revision = 'bd641f727ed0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.alter_column('summary',
               existing_type=sa.VARCHAR(length=511),
               nullable=True)
        batch_op.alter_column('publication_date',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('author_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.alter_column('author_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('publication_date',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('summary',
               existing_type=sa.VARCHAR(length=511),
               nullable=False)

    # ### end Alembic commands ###
