"""2nd

Revision ID: 73528a0b20bf
Revises: 3c0a82dd581c
Create Date: 2023-05-08 18:22:32.398292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73528a0b20bf'
down_revision = '3c0a82dd581c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
