"""fix book model

Revision ID: 73ee0610b080
Revises: 0ce2584aec8f
Create Date: 2023-05-03 22:07:14.491485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73ee0610b080'
down_revision = '0ce2584aec8f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
