"""initial migration

Revision ID: 80afc5fab85c
Revises: 
Create Date: 2023-07-04 22:15:19.137614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80afc5fab85c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
