"""Fix misspeling in Book

Revision ID: 898a5bdaefb3
Revises: ce6dd1142dbf
Create Date: 2023-12-08 15:17:22.079693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '898a5bdaefb3'
down_revision: Union[str, None] = 'ce6dd1142dbf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('publication_date', sa.Date(), nullable=True))
    op.drop_column('book', 'publication_data')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('publication_data', sa.DATE(), nullable=True))
    op.drop_column('book', 'publication_date')
    # ### end Alembic commands ###
