"""Added field books to Author model

Revision ID: 8d69ab31325d
Revises: 4df6e2f09cd3
Create Date: 2023-04-07 15:52:39.417042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d69ab31325d'
down_revision = '4df6e2f09cd3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
