"""Initial migration

Revision ID: 8f4968309dd5
Revises: f05fc2b60ad4
Create Date: 2023-05-04 16:03:57.937211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f4968309dd5'
down_revision = 'f05fc2b60ad4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
