"""fixed bio field

Revision ID: b9c9578f05ce
Revises: 937199610189
Create Date: 2023-05-04 16:05:34.547865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9c9578f05ce'
down_revision = '937199610189'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('author', sa.Column('bio', sa.String(length=255), nullable=False))
    op.drop_column('author', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('author', sa.Column('description', sa.VARCHAR(length=255), nullable=False))
    op.drop_column('author', 'bio')
    # ### end Alembic commands ###
