"""Initial migration

Revision ID: cb88bfe8a17a
Revises: 5a1dc33d4359
Create Date: 2023-08-25 12:18:12.406974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb88bfe8a17a'
down_revision: Union[str, None] = '5a1dc33d4359'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('publication_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book', 'publication_date')
    # ### end Alembic commands ###
