"""3nd

Revision ID: cbefa5d81e0c
Revises: 73528a0b20bf
Create Date: 2023-05-08 18:31:07.619866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbefa5d81e0c'
down_revision = '73528a0b20bf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
