"""Second migration

Revision ID: d30c45003e6c
Revises: 7a54007e4be9
Create Date: 2023-04-07 20:08:12.433164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd30c45003e6c'
down_revision = '7a54007e4be9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
