"""init

Revision ID: d779e848f634
Revises: 06ddbbd6d5ad
Create Date: 2023-05-03 18:38:13.674176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd779e848f634'
down_revision = '06ddbbd6d5ad'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
