"""Your migration message

Revision ID: d97da1747409
Revises: c6a65661feb1
Create Date: 2023-05-02 14:57:20.130645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd97da1747409'
down_revision = 'c6a65661feb1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
