"""Add field to Book model

Revision ID: f3a77aa8878a
Revises: 8ed814e0aeab
Create Date: 2023-08-24 12:00:25.147774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3a77aa8878a'
down_revision: Union[str, None] = '8ed814e0aeab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('summary', sa.String(length=511), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'summary')
    # ### end Alembic commands ###
