"""2

Revision ID: f47e77ae70ba
Revises: 3ab78df8af0a
Create Date: 2023-07-05 20:30:57.076958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f47e77ae70ba'
down_revision = '3ab78df8af0a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
