"""create book table

Revision ID: 022c4355e290
Revises: 2f338394f388
Create Date: 2023-03-31 16:07:41.963460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '022c4355e290'
down_revision = '2f338394f388'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
